name: flutter_starter # TODO change app name
description: "A new Flutter project." # TODO change app description
publish_to: 'none' # Keep as is
version: 0.1.0 # TODO update then when releasing

# Flutter 3.24.3
environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  get_it: ^8.0.0
  shared_preferences: ^2.3.2
  dio: ^5.7.0
  dio_cache_interceptor: ^3.5.0
  easy_localization: ^3.0.7
  # dart run flutter_native_splash:create
  flutter_native_splash: ^2.4.1

  # ?Anaylytics?
  # firebase_analytics: ^11.3.3
  # firebase_core: ^3.6.0
  # firebase_crashlytics: ^4.1.3
  # firebase_performance: ^0.10.0+8
  # firebase_performance_dio: ^0.7.1
  # ?In-app subscriptions?
  # purchases_flutter: ^8.1.2
  # purchases_ui_flutter: ^8.1.3
  # ?Permissions?
  # permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  # dart run build_runner watch --delete-conflicting-outputs
  build_runner: ^2.4.13
  # dart run change_app_package_name:main <com.new.package.name>
  change_app_package_name: ^1.4.0
  # dart run flutter_launcher_icons:main
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter_native_splash:
  color: "FFFFFF"
  image: assets/splash/splash.png

flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/images/
  - assets/icon/
  - assets/splash/
  - assets/fonts/
