name: flutter_starter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

# Flutter 3.24.3
environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
